### ISSUE TITLE
Please make the key public

### ISSUE THREAD

**Issue by serieuxchat** [filom/ASN1Decoder#1]
The certificate pinning example won't work for me because the members of PublicKey are inaccessible :-(
Could you make them public?

**Comment by filom** [comment]
Thanks for the highlighting, I've made publicKey's methods public as it should be.
Updated in the CocoaPods version 1.0.3.

**Comment by flockoffiles** [comment]
Thanks very much for fixing it so fast!
I have created a small pull request to have the scheme shared (for Carthage support).
If you agree with it, could you merge it?
