### ISSUE TITLE
checkValidity for CRL certificates.

### ISSUE THREAD

**Issue by algonrey** [filom/ASN1Decoder#11]
Hi, first of all, wow... great job with this library :) 

Now, there is a way to make the checkValidity method works with CRL certificates? as i can see in the object created, the values for the dates are the following:

        UTCTIME : 2019-05-08 22:00:35 +0000
        UTCTIME : 2019-06-07 22:00:35 +0000

and with a CRL, the values are:

        SEQUENCE {
            UTCTIME : 2014-01-20 15:45:35 +0000
            GENERALIZEDTIME : 2060-12-31 15:24:38 +0000
        }

Is there any chance to get the dates correctly for the CRL??

Thank you!

**Comment by filom** [comment]
Hi! 
What do you specifically mean with "CRL certificate" ? A CRL file is not a certificate, although it is encoded with ASN.1. 
The checkValidity method is specific for X.509  certificate, so it's not going to work with a CRL, if you for example tried to instantiate a X509Certificate with a CRL file.
CRL should have a different class to help parse a CRL structure.

**Comment by algonrey** [comment]
Sorry for the misunderstanding, effectively i mean CRL file.

Is in your plans to do a parser for this kind of file on future releases? I will much appreciated.

Thanks again for your work.

Regards.

**Comment by filom** [comment]
I haven't plan a release for CRL.
Anyhow if you just need the CRL dates interval, you can just use this:
```
let asn1 = try ASN1DERDecoder.decode(data: crlData)
let dateFrom = asn1.first?.sub(0)?.sub(3)?.value as? Date
let dateTo = asn1.first?.sub(0)?.sub(4)?.value as? Date
```

**Comment by algonrey** [comment]
Thanks @filom i will try it :)
