### ISSUE TITLE
receipt verification

### ISSUE THREAD

**Issue by tcurdt** [filom/ASN1Decoder#14]
I am currently investigating local receipt verification for macOS using `ASN1Decoder`.

The problem is that `ASN1Decoder.PKCS7.ReceiptInfo` does not include all fields required for validation.

According to the docs below I'd also need the following to be exposed that are currently missing:

1. Opaque Value
2. SHA-1 Hash

from `ASN1Decoder.PKCS7.ReceiptInfo`. 

https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW2

**Comment by filom** [comment]
Added the fields, now receipt should be complete.

**Comment by tcurdt** [comment]
Should I keep this open until the next release? Otherwise it should be fine to close I guess.
Thanks for the quick change!
