### ISSUE TITLE
Added files has no reference in the project

### ISSUE THREAD

**Issue by gmromzky** [filom/ASN1Decoder#20]
The following files aren't referenced in the project and causing error on compiling:
ASN1DistinguishedNames.swift
X509Extension.swift
X509PublicKey.swift

<img width="198" alt="Add files" src="https://user-images.githubusercontent.com/47657439/70232301-12bb8080-1797-11ea-9ca8-0959b038948f.png">

**Comment by filom** [comment]
Thanks for the hint. It should be fixed now.
