### ISSUE TITLE
Subject Alternative Names(SAN) containing ip address not are considerd and processed

### ISSUE THREAD

**Issue by maverick-b** [filom/ASN1Decoder#25]
i have a self signed certifiate on my server which has combination of DNS and IP in SAN.
If any certificate has IP address present its not taken into account since its only expecting strings and processing via valueAsStrings(shown below from X509Extension file)

var valueAsStrings: [String] {
        var result: [String] = []
        for item in block.sub?.last?.sub?.last?.sub ?? [] {
            if let name = **item.value as? String** {
                result.append(name)
            }
        }
        return result
    }

While for DNS this works but for IP it fails since its added as Data directly in the parse method in ASN1DERDecoder file.

 // custom/private tag
 let contentData = try loadSubContent(iterator: &iterator)
  if let str = String(data: contentData, encoding: .utf8) {
       asn1obj.value = str
      } else {
           **asn1obj.value = contentData**
 }

Another thing i observed was, for few IP's example(127.0.01, 10.01.10.4, etc) which can be successfully encoded using UTF8 are encoded in wrong strings while others(169.10.23.23, 132.186.85.6) which can't be encoded are added as Data  itself.

@filom Are you planning to include this scenario in any of te future releases?
i know its a rare case but it would be great if you could handle these.

**Comment by filom** [comment]
Just add 5fdda99f0ccb4f320142af24b52006c4a6d9f450 to support multiple SAN sub-types included IP-Address.

**Comment by filom** [comment]
It's now available on cocoapod version 1.5
