### ISSUE TITLE
Wrong PKCS7 signature data 

### ISSUE THREAD

**Issue by schwmi** [filom/ASN1Decoder#29]
When parsing the PKCS7 signatureData from AppStore Receipts, we may end up with the field:

```
    OCTETSTRING {
        GRAPHICSTRING: 3 bytes
        CONTEXTSPECIFIC(11): 
        APPLICATION(2) {
            NUMERICSTRING {
                APPLICATION(8): 
            }
        }
        APPLICATION(7)
    }
```

instead of
```
Optional<ASN1Object>
  ▿ some : OCTETSTRING: 256 bytes
```

If so, accessing the `SignatureInfo`'s `signatureData` field yields nil  (as `signature?.value` == nil). Access via `signature.rawValue` returns 256 bytes.

I've attached a sample b64 sandbox receipt which results in such behavior:

[receipt.b64.txt](https://github.com/filom/ASN1Decoder/files/5482174/receipt.b64.txt)

**Comment by filom** [comment]
Fixed with b1cd17c9950a764df657de036f800869fd2fdfaf
