### ISSUE TITLE
Not getting the correct values from extention for Basic constrainsts and exdKeyUsage extentions

### ISSUE THREAD

**Issue by maverick-b** [filom/ASN1Decoder#30]
After decoding the Basic constraints block always seems to have same results for different server certificates
`SEQUENCE {
    OBJECTIDENTIFIER: 2.5.29.19 (basicConstraints)
    BOOLEAN: true
    OCTETSTRING {
        SEQUENCE
    }
}`
While isCritical field seems to correct, but i couldn't find a way to get the CA and path length fields.

`SEQUENCE {
    OBJECTIDENTIFIER: 2.5.29.37 (extKeyUsage)
    OCTETSTRING {
        SEQUENCE {
            OBJECTIDENTIFIER: 1.3.6.1.5.5.7.3.2 (clientAuth)
            OBJECTIDENTIFIER: 1.3.6.1.5.5.7.3.1 (serverAuth)
        }
    }
}
`
As for **extKeyUsage** while the data is being decoded correctly, but the value property of Extension class returns only one result, since its fetchcing only leaf  value because of ` firstLeafValue(block: ASN1Object) -> Any?` function being used.
This is similar in case of using `subject(oid: String) -> String?` method, since it uses ` findOid(_ oid: String) -> ASN1Object?` which again returns the leaf block. Can you please add methods which will return all values instead of just leaf.

While i also observed inconsistency in getting the **subjectKeyIdentifier** extension value. While it provides correct ContextSpecific bytes for certificates signed by proper, CA  it's decoded as following for my self signed one.
`SEQUENCE {
    OBJECTIDENTIFIER: 2.5.29.14 (subjectKeyIdentifier)
    OCTETSTRING {
        OCTETSTRING {
            APPLICATION(2)
        }
    }
}`

@filom Can you please provide a quick fix for these. Also what causes **subjectKeyIdentifier** to be decoded as Application instead of ContextSpecific bytes

**Comment by filom** [comment]
To get the extKeyUsage (2.5.29.37) you can already use the property `extendedKeyUsage` of `X509Certificate`,
while for the other let me check.

**Comment by maverick-b** [comment]
@filom Thanks for the really quick updates. But one question why are the classes inside **X509ExtensionClasses** used as an extension inside **X509Extension**, since although from **extensionObject** method correct class is initialized, but still an object of **X509Extension** is returned, so the caller won't be able to typecast to appropriate class because of **X509ExtensionClasses** being inside X509Certificate and are inaccesible.
`public func extensionObject(oid: String) -> X509Extension? {
        return block1[X509BlockPosition.extensions]?
            .findOid(oid)?
            .parent
            .map { oidExtensionMap[oid]?.init(block: $0) ?? X509Extension(block: $0) }
    }`
I am trying to access these extension classes in a wrong way or these should exist outside X509Extension?

Also using any of these two method is till returing a single value for common name, while my certificate has two
`  public func subject(oid: String) -> String?`
`public func subject(dn: ASN1DistinguishedNames) -> String?`
Can you suggest right approach to find both values.

**Thanks a ton in advance.**

**Comment by filom** [comment]
You can check how to use the detailed extensions on the test class `ASN1DecoderX509Extensions`.
About the single return of common name I thought they where unique, as e.g. website certificate you cannot have more than one CN and additional names needs to be in the extension, but I'll check the rfc.
