### ISSUE TITLE
Unexposed receipt properties

### ISSUE THREAD

**Issue by schwmi** [filom/ASN1Decoder#31]
When verifying apple receipts we need the receipt data for checking the signature. Currently, we can access the correct data blob for verification via `let receiptData = pkcs7.mainBlock.findOid(.pkcs7data)?.parent?.sub?.last?.sub(0)?.rawValue`. 
But it seems there is no public api yet for accessing the required data and we have to import the ASN1Decoder via `@testable` to access the internal `mainBlock` property.

Furthermore for parsing undocumented apple receipt elements we have to access the receipt block via `receiptBlock = pkcs7.mainBlock.findOid(.pkcs7data)?.parent?.sub?.last?.sub(0)?.sub(0)`. Also this is currently not accessible via public api. 

One possible solution to fix this issue would be to expose `pkcs7.mainBlock: ASN1Object` as public property on PKCS7. 
Or is there another way for accessing those properties?

**Comment by filom** [comment]
Fixed with commit b939294834fd5d87c3d17c49e7bcc3fbc6426bbe rel (1.7.1)

**Comment by schwmi** [comment]
Thanks 👍
