### ISSUE TITLE
How to extract subjectKeyIdentifier from X509Certificate

### ISSUE THREAD

**Issue by Kurt57** [filom/ASN1Decoder#35]
hi all, 

how I can fetch subjectKeyIdentifier and its rawValue?

**Comment by filom** [comment]
Hi, subjectKeyIdentifier (2.5.29.14) is an extension and can be extracted with the following code:

```
if let ext = x509.extensionObject(oid: .subjectKeyIdentifier), let value = ext.value as? Data {
 // here value contains the data
}
```

**Comment by Kurt57** [comment]
Hi @filom thanks a lot but how I can get raw Value xx:xx:xx....

and SAN List?
