### ISSUE TITLE
Can ASN1Object be an open class?

### ISSUE THREAD

**Issue by flockoffiles** [filom/ASN1Decoder#4]
Would it be possible to make ASN1Object an open class (instead of public), so that creating an extension of it becomes possible?
Also, would it be possible to make ASN1Identifier a public class?

**Comment by flockoffiles** [comment]
In addition, it would be nice if the fields of ASN1Object (sub, data, etc.) were publicly accessible.

For instance, I am trying to parse a DER-encoded public key and extract the raw part of (excluding the header) in order to pass it to Apple's crypto APIs.

I could do it as follows (but currently can't):

let decodedPublicKeyObjects = try ASN1DERDecoder.decode(data: QB_DER)
let barePublicKey = decodedPublicKeyObjects[0].sub![1].value! as! Data

Both 'sub' and 'value' are inaccessible outside of the ASN1Decoder framework :-(

**Comment by filom** [comment]
Some property I prefer to keep internal for possible future development, but I'll public more information with safer methods, like in the following line:

let barePublicKey = decodedPublicKeyObjects[0].sub(1)?.rawValue as? Data

rawValue gives you the raw der encoded content
and value gives you the Swift decoded object whenever is possible.

**Comment by flockoffiles** [comment]
This would be really awesome! Then I won't need to use a fork.
