### ISSUE TITLE
Deployment version is wrong

### ISSUE THREAD

**Issue by hollanderbart** [filom/ASN1Decoder#5]
https://github.com/filom/ASN1Decoder/blob/f19cbfa1528ab11b43f4d1e4b96cf36b760a49fe/ASN1Decoder.xcodeproj/project.pbxproj#L288

The deployment version is on iOS 10.3 while you're supporting iOS 9.0+. This gives issues for my project when I want to support iOS 9.3. Could you please change the deployment version to iOS 9.0?

**Comment by filom** [comment]
fixed

**Comment by hollanderbart** [comment]
Thanks!
