### ISSUE TITLE
Public Key decoder can't parse a public key from a Google certificate

### ISSUE THREAD

**Issue by flockoffiles** [filom/ASN1Decoder#7]
I found out that the class PublicKey fails to extract key data from some certificates.
Here is an example: https://wetransfer.com/downloads/96a5a6e52e5441be44457ab62241144920180403123004/738fcb45b467fcd8e797031159b2d5f520180403123004/2095f9

(It's a Google certificate from https://www.google.nl)

The problem lies in this method:

```swift
    public var key: Data? {
        if let keyBlock = pkBlock.sub?.last {
            if let keyBlockValue = firstLeafValue(block: keyBlock) as? Data {
                do {
                    let asn1PkBlock = try ASN1DERDecoder.decode(data: keyBlockValue)
                    return firstLeafValue(block: asn1PkBlock[0]) as? Data
                } catch {
                    return keyBlockValue
                }
            }
        }
        return nil
    }

```

In the certificate in question, the public key is an EC key:
SEQUENCE {
    SEQUENCE {
        OBJECTIDENTIFIER : 1.2.840.10045.2.1 (ecPublicKey)
        OBJECTIDENTIFIER : 1.2.840.10045.3.1.7 (prime256v1)
    }
    BITSTRING : 65 bytes
}

The code above first tries to parse the bit string as if it were an ASN.1 object in itself. For most EC keys that would fail, but for some the parser will succeed, but give an incorrect value, so the key will be misinterpreted as an RSA key.

I think, it would be more safe to check the encryption algorithm type first.
E.g.

```swift

guard let encryptionAlgorithmId = publicKeyInfo.sub(0)?.sub(0)?.value as? String,
        let keyData = publicKeyInfo.sub(1)?.value as? Data else {
            return nil
    }
    
    if encryptionAlgorithmId == "1.2.840.10045.2.1" {
       // This is an EC public key
        return keyData
    } else if encryptionAlgorithmId == "1.2.840.113549.1.1.1" {
        // Parse the RSA key, as before
       guard let publicKeyAsn1Objects = (try? ASN1DERDecoder.decode(data: keyData)) else {
            return nil
        }
        guard let publicKeyModulus = publicKeyAsn1Objects.first?.sub(0)?.value as? Data else {
            return nil
        }
        return publicKeyModulus
    }
    // Some unsupported algorithm type
    return nil

```

**Comment by filom** [comment]
Thanks for notice it and for the suggested solution. Fixed on tag 1.2
